# Generated by Django 4.1.9 on 2023-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_transceiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transceivertype',
            name='profile',
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='physic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='rx_power_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='rx_power_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='tx_power_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='tx_power_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.DeleteModel(
            name='TransceiverTypeProfile',
        ),
    ]
