# Generated by Django 4.1.9 on 2023-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_transceiver', '0002_remove_transceivertype_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transceivertype',
            name='rx_power_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='rx_power_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='tx_power_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='tx_power_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
