# Generated by Django 4.1.9 on 2023-05-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_transceiver', '0003_alter_transceivertype_rx_power_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransceiverTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transceivertype',
            name='profiles',
            field=models.ManyToManyField(related_name='choices', to='netbox_transceiver.transceivertypeprofile'),
        ),
    ]
