# Generated by Django 4.1.9 on 2023-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_transceiver', '0005_rename_choice_transceivertypeprofile_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transceivertypeprofile',
            options={'ordering': ('group', 'profile')},
        ),
        migrations.AddConstraint(
            model_name='transceivertypeprofile',
            constraint=models.UniqueConstraint(fields=('group', 'profile'), name='netbox_transceiver_transceivertypeprofile_unique_group_profile'),
        ),
    ]
