# Generated by Django 4.1.9 on 2023-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_transceiver', '0006_alter_transceivertypeprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transceiver',
            name='module',
        ),
        migrations.AlterField(
            model_name='transceivertype',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='netbox_transceiver.transceivertypeprofile'),
        ),
    ]
