# Generated by Django 4.1.9 on 2023-05-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_transceiver', '0007_remove_transceiver_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transceiver',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='transceiver_profile', to='netbox_transceiver.transceivertypeprofile'),
            preserve_default=False,
        ),
    ]
